# Generated by Django 2.1.2 on 2018-11-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='ano',
            field=models.IntegerField(default=2018),
        ),
    ]
