# Generated by Django 2.1.2 on 2018-12-11 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chamada', '0004_auto_20181203_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamada',
            name='data',
            field=models.DateField(default=datetime.datetime(2018, 12, 11, 10, 39, 15, 94458, tzinfo=utc)),
        ),
    ]
